"""add table statement

Revision ID: 7b21ec2eb623
Revises: 
Create Date: 2026-03-16 19:27:55.167467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b21ec2eb623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit_total', sa.Float(), nullable=False),
    sa.Column('credit_total', sa.Float(), nullable=False),
    sa.Column('net_balance', sa.Float(), nullable=False),
    sa.Column('number_of_transactions', sa.Integer(), nullable=False),
    sa.Column('top_expenses', sa.String(), nullable=False),
    sa.Column('top_incomes', sa.String(), nullable=False),
    sa.Column('transaction_list_filtered', sa.String(), nullable=False),
    sa.Column('debit_list', sa.String(), nullable=False),
    sa.Column('credit_list', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    # ### end Alembic commands ###
