"""Change transaction table definition

Revision ID: 8d7baa1e5aa6
Revises: 8fc82667ae01
Create Date: 2026-07-31 13:03:26.319289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d7baa1e5aa6"
down_revision: Union[str, Sequence[str], None] = "8fc82667ae01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("type", sa.String(), nullable=False))
    op.add_column("transactions", sa.Column("amount", sa.Float(), nullable=False))
    op.drop_column("transactions", "debit")
    op.drop_column("transactions", "credit")
    # ### end Alembic commands ###al


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("credit", sa.FLOAT(), nullable=True))
    op.add_column("transactions", sa.Column("debit", sa.FLOAT(), nullable=True))
    op.drop_column("transactions", "amount")
    op.drop_column("transactions", "type")
    # ### end Alembic commands ###
