"""remove the balace column from transaction

Revision ID: 8fc82667ae01
Revises: 85d827691428
Create Date: 2026-06-29 19:09:11.155583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc82667ae01'
down_revision: Union[str, Sequence[str], None] = '85d827691428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('balance', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
