"""switch table name

Revision ID: 933f53fe3259
Revises: f757e920ea95
Create Date: 2026-04-14 20:20:24.309569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933f53fe3259'
down_revision: Union[str, Sequence[str], None] = 'f757e920ea95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_description', sa.String(), nullable=False),
    sa.Column('transaction_debit', sa.Float(), nullable=True),
    sa.Column('transaction_credit', sa.Float(), nullable=True),
    sa.Column('transaction_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('statement_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('transaction_description', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_debit', sa.FLOAT(), nullable=True),
    sa.Column('transaction_credit', sa.FLOAT(), nullable=True),
    sa.Column('transaction_balance', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_transaction_statement_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
