"""Add more fields to user table

Revision ID: af55fa9729c4
Revises: 1efc9e7551ba
Create Date: 2026-10-08 22:40:17.766344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af55fa9729c4'
down_revision: Union[str, Sequence[str], None] = '1efc9e7551ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_id', sa.String(length=36), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.drop_column('users', 'supabase_id')
    # ### end Alembic commands ###
