"""add date to statemenet

Revision ID: c6282885d95d
Revises: 7b21ec2eb623
Create Date: 2026-03-16 20:25:30.017068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6282885d95d'
down_revision: Union[str, Sequence[str], None] = '7b21ec2eb623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'date')
    # ### end Alembic commands ###
